version: '3.8'

services:
  trustpilot-scraper:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      # Mount current directory for development (comment out for production)
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M 